# Generated by Django 4.2.9 on 2024-03-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitors',
            options={'verbose_name_plural': 'List of Offender Logs'},
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='date_created',
        ),
        migrations.AddField(
            model_name='visitors',
            name='comment',
            field=models.TextField(default='No comment'),
        ),
    ]
