# Generated by Django 4.2.9 on 2024-03-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0002_alter_visitors_options_remove_visitors_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='comment',
            field=models.TextField(),
        ),
    ]
