# Generated by Django 4.2.9 on 2024-03-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0003_alter_visitors_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='case_id',
            field=models.CharField(default='No case ID', max_length=200),
        ),
    ]
