# Generated by Django 4.2.9 on 2024-03-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0006_visitors_comments_alter_visitors_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='comments',
        ),
        migrations.AlterField(
            model_name='visitors',
            name='comment',
            field=models.TextField(default='No comment', max_length=200),
        ),
    ]
