# Generated by Django 4.2.9 on 2024-03-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0008_rename_comment_visitors_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='comments',
        ),
        migrations.AddField(
            model_name='visitors',
            name='comment',
            field=models.TextField(default='No comment', max_length=200),
        ),
    ]
